name: Release and package binaries

on:
  release:
    types: [created]

defaults:
  run:
    shell: bash

jobs:
  package:
    strategy:
      matrix:
        include:
          - { target: x86_64-unknown-linux-musl, archive: tar.gz }
          - { target: x86_64-apple-darwin,       archive: zip }
          - { target: x86_64-pc-windows-gnu,     archive: zip }
    name: Build ${{ matrix.target }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install dependencies
        run: sudo apt-get install libgtk-4-dev build-essential gir1.2-gtk-4.0

      - name: Build and upload
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: stable
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
